<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Choisir un mot de passe</title>
</head>
<body>
    <h1>Choisissez un mot de passe</h1>
    <form action="decrypt_password.php" method="post">
    <label for="password">Mot de passe :</label>
    <input type="password" name="password" id="password" required><br>

    <label for="hash">Hash :</label>
    <input type="text" name="hash" id="hash" required><br>

    <button type="submit">Vérifier</button>
</form>

</body>
</html>
